#!/usr/bin/env node
/* ============================================================================
   Write web/js/config.js from environment variables at build time.
   Subsel Tech Solutions Pvt Ltd

   Use this when you would rather not commit a project URL and key, or when one
   repository deploys to several environments:

     Netlify / Cloudflare Pages   Build command: node scripts/write-config.mjs
     Vercel                       Build command: node scripts/write-config.mjs
     Locally                      SUPABASE_URL=… SUPABASE_ANON_KEY=… npm run config

   Set SUPABASE_URL and SUPABASE_ANON_KEY in the host's environment settings.
   Never set SUPABASE_SERVICE_ROLE_KEY for a static site — nothing in BunkSoft
   uses it, and a build that exposed it would hand over every customer's data.
   ========================================================================== */
import fs from 'fs';
import path from 'path';

const url = (process.env.SUPABASE_URL || '').trim().replace(/\/+$/, '');
const key = (process.env.SUPABASE_ANON_KEY || '').trim();
const out = path.resolve('web/js/config.js');

const die = msg => { console.error('write-config: ' + msg); process.exit(1); };

if (!url || !key) {
  die('set SUPABASE_URL and SUPABASE_ANON_KEY.\n' +
      '  Both are under Project Settings -> API in the Supabase dashboard.');
}
if (!/^https:\/\/[a-z0-9-]{1,64}\.supabase\.(co|in)$/i.test(url)) {
  die(`SUPABASE_URL does not look like a project URL: ${url}\n` +
      '  Expected something like https://abcdefgh.supabase.co');
}
/* An anon key is a JWT whose payload says "anon". A service_role key is the
   same shape, so check before writing it into a public file. */
if (!/^ey[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(key) && !/^sb_publishable_/.test(key)) {
  die('SUPABASE_ANON_KEY does not look like a Supabase key.');
}
try {
  const payload = JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString('utf8'));
  if (payload.role && payload.role !== 'anon') {
    die(`refusing to write a "${payload.role}" key into a file served to browsers.\n` +
        '  Use the anon public key. The service_role key bypasses every security policy.');
  }
} catch { /* not a JWT (a sb_publishable_ key, say) — the shape check above stands */ }

fs.writeFileSync(out,
`/* Generated by scripts/write-config.mjs — do not edit by hand.
   Built ${new Date().toISOString()} */
window.BUNKSOFT_CONFIG = {
  supabaseUrl:     ${JSON.stringify(url)},
  supabaseAnonKey: ${JSON.stringify(key)}
};
`);
console.log(`write-config: wrote ${path.relative(process.cwd(), out)} for ${url}`);
